### ISSUE TITLE
[TODO] Complete unit test coverage

### ISSUE THREAD

**Issue by kiavash-at-work** [ashuio/shavee#21]
Current missing unit tests coverage as of PR #19 :
 - [ ] Pam Module functions in `shavee-pam::lib.rs`
 - [ ] All Yubikey related functions
 - [ ] Simple (2~4 lines) functions in `shavee-core::logic.rs`
